[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "telegive-dashboard"

[services.source]
repo = "telegive-dashboard"
branch = "main"

[services.variables]
NODE_ENV = "production"
PORT = "3000"
VITE_APP_NAME = "Telegive Dashboard"
VITE_APP_VERSION = "1.0.0"
VITE_ENABLE_REAL_TIME_UPDATES = "true"
VITE_ENABLE_ANALYTICS = "false"
VITE_ENABLE_DEBUG_MODE = "false"
VITE_MAX_FILE_SIZE = "52428800"
VITE_ALLOWED_IMAGE_TYPES = "image/jpeg,image/png,image/gif"
VITE_ALLOWED_VIDEO_TYPES = "video/mp4,video/mov,video/avi"
VITE_THEME_PRIMARY_COLOR = "#3b82f6"
VITE_THEME_SECONDARY_COLOR = "#64748b"
VITE_ITEMS_PER_PAGE = "20"

