[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[services.variables]
NODE_ENV = "production"
PORT = "3000"
VITE_TELEGIVE_AUTH_URL = "https://web-production-ddd7e.up.railway.app"

